### ISSUE TITLE
release 0.3

### ISSUE THREAD

**Issue by rhelmer** [mozilla-ion/ion-basic-study#24]
We need to cut a release now that badging is enabled, and to pick up the badging changes from https://github.com/mozilla-ion/ion-core-addon/issues/246 and also just to get the latest changes so the study add-on `rally.js` is compatible with the core.

@Dexterp37 I know you are working on release process, https://github.com/mozilla-ion/ion-core-addon/blob/master/docs/STUDY_PUBLISHING.md is the latest we have for study add-ons. Are you covering this in your current work or should we stick with that for now?

**Comment by Dexterp37** [comment]
> @Dexterp37 I know you are working on release process, https://github.com/mozilla-ion/ion-core-addon/blob/master/docs/STUDY_PUBLISHING.md is the latest we have for study add-ons. Are you covering this in your current work or should we stick with that for now?

Nope, the current work was only for the core addon. We should stick to the current study publishing process for now

**Comment by rhelmer** [comment]
Ugh, so I *did* get this submitted to AMO (built off the v0.3.0 tag) but I had to make a few changes:

- change version number to 0.3.0 (we made the same "2.0" jump as the core add-on which is probably my fault, I'll file an issue to fix this).
- removed the 2.0 version from AMO
- we cannot change the addon ID ourselves, so I set it back to "ion-basic-study" for the moment. we need to figure out if AMO folks can change this or if they want us to just upload a new one.

I went ahead and created a `release-v0.3.0` branch which has these changes, and the `v0.3.0` tag is based on these, so it is exactly what I uploaded to AMO.

**Comment by rhelmer** [comment]
We are currently waiting on review.

**Comment by wagnerand** [comment]
> Ugh, so I _did_ get this submitted to AMO (built off the v0.3.0 tag) but I had to make a few changes:
> 
>     * change version number to 0.3.0 (we made the same "2.0" jump as the core add-on which is probably my fault, I'll file an issue to fix this).
> 
>     * removed the 2.0 version from AMO

Note that updates for existing users won't work if the version number is lower than a previously submitted version. If you'd like existing users to get updated to this or subsequent updates, the version number must be higher than the current highest version number.
> 
>     * we cannot change the addon ID ourselves, so I set it back to "ion-basic-study" for the moment. we need to figure out if AMO folks can change this or if they want us to just upload a new one.

Unfortunately, the ID can't be changed. It's the unique identifier and making changes would cause breaking and side-effects.

**Comment by rhelmer** [comment]
> > Ugh, so I _did_ get this submitted to AMO (built off the v0.3.0 tag) but I had to make a few changes:
> > ```
> > * change version number to 0.3.0 (we made the same "2.0" jump as the core add-on which is probably my fault, I'll file an issue to fix this).
> > 
> > * removed the 2.0 version from AMO
> > ```
> 
> Note that updates for existing users won't work if the version number is lower than a previously submitted version. If you'd like existing users to get updated to this or subsequent updates, the version number must be higher than the highest version number of any approved version.

Makes sense, I went ahead and deleted the old release (it was non-functional and required disabling signing etc. so not many people should have it).

> 
> > ```
> > * we cannot change the addon ID ourselves, so I set it back to "ion-basic-study" for the moment. we need to figure out if AMO folks can change this or if they want us to just upload a new one.
> > ```
> 
> Unfortunately, the ID can't be changed. It's the unique identifier and making changes would cause breaking and side-effects.

No worries at all, I think we'll probably be better off just doing a new product later.

@Dexterp37 on this subject, since this repo is becoming more of a template we should probably not publish the template but instead some actual study based on it, wdyt?

**Comment by rhelmer** [comment]
> > Note that updates for existing users won't work if the version number is lower than a previously submitted version. If you'd like existing users to get updated to this or subsequent updates, the version number must be higher than the highest version number of any approved version.
> 
> Makes sense, I went ahead and deleted the old release (it was non-functional and required disabling signing etc. so not many people should have it).

Well I won't go into gory detail on the signing but quick correction, suffice to say it's a pre-release version that we don't need to support right now, and we could push an update to self-delete if/when we decide to create this under a new extension per my comment :) Thanks!

**Comment by Dexterp37** [comment]
> @Dexterp37 on this subject, since this repo is becoming more of a template we should probably not publish the template but instead some actual study based on it, wdyt?

I think you're right, we'll need a "demo study" of some sort. I think we should file an issue and defer that. It probably requires to spin up a separate repo so that we don't pollute this template.

**Comment by rhelmer** [comment]
This was approved on AMO!
