### ISSUE TITLE
remove post-1.0 versions and tags

### ISSUE THREAD

**Issue by rhelmer** [mozilla-ion/ion-basic-study#25]
We've published a 2.0 with tags and AMO version, let's start this over. /cc @Dexterp37

**Comment by rhelmer** [comment]
This is done, removed the ion-basic-study 2.0:

- AMO release
- GH release
- git tag

We're on `0.3.0` now!

**Comment by Dexterp37** [comment]
@rhelmer please note that the tags are [still around](https://github.com/mozilla-ion/ion-basic-study/releases). You can remove them by following the process [documented here](https://github.com/mozilla-ion/ion-core-addon/issues/217#issuecomment-741663679).

**Comment by rhelmer** [comment]
> @rhelmer please note that the tags are [still around](https://github.com/mozilla-ion/ion-basic-study/releases). You can remove them by following the process [documented here](https://github.com/mozilla-ion/ion-core-addon/issues/217#issuecomment-741663679).

@Dexterp37 Hm, do you want to remove all releases, not just the post-2.0 one? There was a 0.1 and 0.2 we posted and tested, but we jumped everything to 2.0 at some point so the latter is what I removed.

**Comment by Dexterp37** [comment]
> 
> 
> > @rhelmer please note that the tags are [still around](https://github.com/mozilla-ion/ion-basic-study/releases). You can remove them by following the process [documented here](https://github.com/mozilla-ion/ion-core-addon/issues/217#issuecomment-741663679).
> 
> @Dexterp37 Hm, do you want to remove all releases, not just the post-1.0 one? There was a 0.1 and 0.2 we posted and tested, but we jumped everything to 2.0 at some point so the latter is what I removed.

Ah, good point, nevermind then.
