### ISSUE TITLE
Add project boilerplate (npm, rollup, unit tests)

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-ion/ion-basic-study#8]
As with the mozilla-ion/ion-core-addon, we need some way to manage addon dependencies. We could replicate what we do with the core addon: use NPM for dependencies and Rollup as a packer, mochajs for tests.

**Comment by Dexterp37** [comment]
We should:

- npm support
- eslint support
- web-ext support
- Webextension-polyfill 
- Unit test support (mochajs…) + an example
- Degit or `rally init`

**Comment by marniepw** [comment]
@knowtheory call to update this ticket w/requirements @Dexterp37 mentioned. For example, jumping down to actual study card area.

**Comment by Dexterp37** [comment]
> 
> 
> @knowtheory call to update this ticket w/requirements @Dexterp37 mentioned. For example, jumping down to actual study card area.

That issue needs to happen on a different repo: I filed mozilla-ion/ion-core-addon#138 for it!
